name: bisimo
description: "Bisimo - Aplikasi Analisis dan Regulasi Emosi untuk Murid Tunarungu"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Navigation & Routing
  go_router: ^14.6.2

  # UI Helpers
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1

  # Camera (placeholder untuk nanti)
  camera: ^0.11.0+2

  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.3.3

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Screens/
    - assets/Screens/Auth/
    - assets/Screens/Cimo/
    - assets/UIUX/
    - assets/Fonts/
